### ISSUE TITLE
このリポジトリのフォーク設定

### ISSUE THREAD

**Issue by Tatsumi0000** [Tatsumi0000/barter#2]
### なぜやるか
- 今回、このリポジトリはフォークして開発を進める予定だから。
### 終了条件
- `git remote -v`したときににこのリポジトリのURLが`upstream`にある。
- 手元にフォークしたリポジトリをクローンする。

**Comment by Reo-Ozaki** [comment]
おわったおー

**Comment by ryusei-kuratomi** [comment]
終わりました

**Comment by taishiro-terada** [comment]
終わった！
