### ISSUE TITLE
CI/CD環境を整備する

### ISSUE THREAD

**Issue by korosuke613** [Tatsumi0000/barter#5]
### なぜやるか
- テストを手動でするのが面倒だから
- デグレードを防ぎたいから
- masterを更新するたびに手動でデプロイする必要があるから。

### 終了条件
- masterが更新されるたびにサイトが最新の状態になる．

#### 備考，関連資料（省略可）
- 西田くんが楽したいらしい
- netlifyでやりたいらしい（github pagesでも良い気がするけど）
- CI/CDのおすすめはGitHub ActionsかCircleCIがおすすめです。(ただデプロイするだけならActionsで良いと思う)
- [actionsのワークフローの書き方](https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions)
- [.circleci/config.ymlの書き方](https://circleci.com/docs/ja/2.0/configuration-reference/#section=configuration)
- netlifyにアップロードしたいなら、secretsにサイトIDとトークンを設定する必要がある([参考](https://medium.com/@kosa3/github-actions%E3%81%A7netlify%E3%81%AB%E8%87%AA%E5%8B%95%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4%E3%81%99%E3%82%8B-22ac30e02528))
- これにアサインされた人は西田くんに聞けばなんとかしてくれると思う

**Comment by Tatsumi0000** [comment]
ありがとうございます。

**Comment by Tatsumi0000** [comment]
> netlifyでやりたいらしい（github pagesでも良い気がするけど）

確かにデプロイするだけならgithub pagesでもいいですね。
そっちの方向で考えてみます。
