### ISSUE TITLE
ポイント送信と履歴の作成

### ISSUE THREAD

**Issue by ryusei-kuratomi** [Tatsumi0000/barter#6]
### なぜやるか
- 相手にポイントを送らなければならないから
- 送ったポイントの履歴が気になるから
### 終了条件
- ポイントを送るボタンの作成
- 送った履歴の提示

**Comment by Tatsumi0000** [comment]
もし、参考にしたサイトなどがあれば、貼っといてください！

**Comment by ryusei-kuratomi** [comment]
了解です⁉

**Comment by ryusei-kuratomi** [comment]
タブ切り替えの参考サイト
https://bagelee.com/design/css/create_tabs_using_only_css/
